### ISSUE TITLE
Logout on page refresh

### ISSUE THREAD

**Issue by GitLukeW** [TeamProductionSystem/Team_Production_System#8]
**Describe the bug**
The current code to login users in not set in state, so it logs out the users every time they refresh the page. 

**To Reproduce**
1. run npm start
2. login
3. refresh page
4. you will then be logged out. 

**Expected behavior**
The expected behavior is the user would stay logged in until they logout. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
N/A

**Comment by nzeager** [comment]
After investigation it turned out that upon login, code was not storing username and token properly. I've submitted a PR with the fix.

**Comment by GitLukeW** [comment]
Thank for contributing to the project and getting this bug worked out!
